### ISSUE TITLE
bruv sorry... but this is plagarism, you should rebrand it:

### ISSUE THREAD

**Issue by webbrowser11** [G1aD05/NIX#1]
NixOS: is an actual os already. and it is copyright claimed so you have yo rebrand this.

**Comment by webbrowser11** [comment]
also did you maybe sorta get inspiration from SkyOS? you know SkyOS is distro-freindly and you could have just forked it.

**Comment by G1aD05** [comment]
What? I did not even think about SkyOS while making this, did SkyOS become something like this? Also wth is nixos...

**Comment by G1aD05** [comment]
Also this is still in beta so I'll rebrand it later.

**Comment by G1aD05** [comment]
I just reviewed the kernel on SkyOS and it doesn't look anything like the one I made

**Comment by webbrowser11** [comment]
ik i was just suggesting it, here is NixOS: https://github.com/NixOS

**Comment by G1aD05** [comment]
Eh I'm sure it's fine that name isn't all caps and has OS at the end

**Comment by webbrowser11** [comment]
ok
